# Generated by Django 2.1.3 on 2018-11-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsmyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('publishdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jpdate', models.DateField()),
                ('jlocation', models.CharField(max_length=100)),
                ('joffsal', models.FloatField()),
                ('jmob', models.CharField(max_length=11)),
            ],
        ),
    ]
